#include "cheddarjack.h"

// Tap Dance declarations
enum {
    BSPC_OOPS,
	TAB_QUOT,
	ENT_OOPS
};

// Tap Dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for KC_0, twice for Backspace
    [BSPC_OOPS] = ACTION_TAP_DANCE_DOUBLE(KC_0, KC_BSPC),
	[TAB_QUOT] = ACTION_TAP_DANCE_DOUBLE(KC_QUOT, KC_TAB),
	[ENT_OOPS] = ACTION_TAP_DANCE_DOUBLE(KC_SLSH, KC_ENT)
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	LAYOUT(
		KC_1, KC_2, KC_3, KC_4, KC_5,	TD(TAB_QUOT),	KC_6, KC_7, KC_8, KC_9, TD(BSPC_OOPS),
		KC_Q, KC_W, KC_F, KC_P, KC_G, 	        	KC_J, KC_L, KC_U, KC_Y, KC_BSPC,
		KC_A, KC_R, KC_S, KC_T, KC_D,	KC_ENT,		KC_H, KC_N, KC_E, KC_I, KC_O,
		MT(MOD_LCTL,KC_Z), KC_X, KC_C, KC_V, KC_B,				KC_K, KC_M, KC_COMM, KC_DOT, TD(ENT_OOPS),
			MT(MOD_LCTL, KC_MINS), KC_LALT, TT(2), LT(1,KC_SPC), KC_LSFT, TT(1), KC_DEL)
		
	,

	LAYOUT(
		KC_ESC, KC_GRV, KC_TILD, KC_TRNS, KC_BSLS, 	 KC_COLN, 	KC_PIPE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_LCBR, 			 	KC_RCBR, KC_UNDS, KC_PLUS, KC_TRNS, KC_TRNS,
		KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_LBRC, 	KC_SCLN, 	KC_RBRC, KC_MINS, KC_EQL, KC_TRNS, KC_TRNS,
		LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), KC_TRNS, 			 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
						  KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, 	KC_TRNS, KC_TRNS, LCTL(KC_PSCR))
						  
	,
	LAYOUT(
		KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, 				KC_COLN, 	KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 			 	KC_TRNS, KC_MS_BTN1, KC_MS_WH_UP, KC_MS_WH_DOWN, KC_MS_BTN2,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_SCLN, 	KC_TRNS, KC_MS_LEFT, KC_MS_UP, KC_MS_DOWN, KC_MS_RIGHT,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 			 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
						  KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, 	KC_TRNS, KC_TRNS, RESET)
						  
	,


};




